### ISSUE TITLE
OHDSI Tool - HADES (optional)

### ISSUE THREAD

**Issue by RaghaSrinivasan** [stjude-biohackathon/KIDS23-Team3#15]
Verify Install

Introductory Tutorials

https://ohdsi.org/ohdsi2022-tutorial/

https://ohdsi.org/open-source-tutorials/

Practice with use cases

Discuss OHDSI tool among team with specific relevance to Integrating SCCRIP Data in OMOP format.

From https://ohdsi.org/software-tools/ below

HADES (previously the OHDSI METHODS LIBRARY) is a collection of open-source R packages that offer functions which can be used together to perform a complete observational study, starting from data in the CDM, and resulting in estimates and supporting statistics, figures, and tables. The packages interact directly with observational data in the CDM, and can be used simply to provide cross-platform compatibility to completely custom analyses, or can provide advanced standardized analytics for population [characterization](https://ohdsi.github.io/TheBookOfOhdsi/Characterization.html), [population-level effect estimation](https://ohdsi.github.io/TheBookOfOhdsi/PopulationLevelEstimation.html), and [patient-level prediction](https://ohdsi.github.io/TheBookOfOhdsi/PatientLevelPrediction.html). HADES supports best practices for use of observational data and observational study design as learned from previous and ongoing research, such as transparency, reproducibility, as well as measuring the operating characteristics of methods in a particular context and subsequent empirical calibration of estimates produced by the methods.

HADES LINKS
Documentation: [Book of OHDSI](https://ohdsi.github.io/TheBookOfOhdsi/OhdsiAnalyticsTools.html#methods-library) • [HADES Web Site](https://ohdsi.github.io/Hades/)
Installation Information: [Click Here](https://ohdsi.github.io/Hades/packages.html)
Source Code: [GitHub](https://github.com/search?q=topic%3Ahades+org%3AOHDSI&type=Repositories)

**Comment by kvegesan-stjude** [comment]
HADES is up and running.
