### ISSUE TITLE
Vocabulary from ATHENA for Synthea data converted into OMOP CDM

### ISSUE THREAD

**Issue by RaghaSrinivasan** [stjude-biohackathon/KIDS23-Team3#4]
https://ohdsi.org/software-tools/

ATHENA allows you to both search and load standardized vocabularies. It is a resource to be used, not a software tool to install. To download a zip file with all Standardized Vocabularies tables select all the vocabularies you need for your OMOP CDM. Vocabularies with standard concepts and very common usage are preselected. Add vocabularies that are used in your source data. Vocabularies that are proprietary have no select button. Click on the “License required” button to incorporate such a vocabulary into your list. The Vocabulary Team will contact you and request you demonstrate your license or help you connect to the right folks to obtain one.

ATHENA LINKS
Vocabularies: [Click Here](http://athena.ohdsi.org/search-terms/terms?_ga=2.224983706.1659300197.1682374443-1497691935.1682374443&_gl=1*1a8ub92*_ga*MTQ5NzY5MTkzNS4xNjgyMzc0NDQz*_ga_BHVF662WPC*MTY4MjM3NDQ0My4xLjEuMTY4MjM3NTcyMy4wLjAuMA..)
Source Code: [GitHub](https://github.com/OHDSI/Athena)
“10-Minute Tutorial” Video: [Click Here](https://youtu.be/2WdwBASZYLk)

**Comment by lindsayevanslee** [comment]
Task marked done in the Project, so closing this issue
