### ISSUE TITLE
Identify Synthetic public-use data

### ISSUE THREAD

**Issue by RaghaSrinivasan** [stjude-biohackathon/KIDS23-Team3#6]
[Conversion from Synthea CSV to OMOP CDM](https://github.com/OHDSI/ETL-Synthea). 

The data we plan to use will likely be https://ohdsi.github.io/ETL-Synthea/ and expertise in R will come in handy to get data loaded.
Infrastructure set up is handled in separate issue. This task can occur concurrently as we can implement this in Hematology Server that already has OHDSI Tools and other infrastructure ready.

**Comment by lindsayevanslee** [comment]
Task marked done in the Project, so closing this issue
