### ISSUE TITLE
Infrastructure set up - PostgreSQL, OHDSI Tools on Azure VM

### ISSUE THREAD

**Issue by RaghaSrinivasan** [stjude-biohackathon/KIDS23-Team3#7]
Install PostgreSQL, JDK, Tomcat, WebAPI, OHDSI Tools - 

OHDSI offers a wide range of open-source tools to support various data-analytics use cases on observational patient-level data. What these tools have in common is that they can all interact with one or more databases [using the Common Data Model (CDM)](https://ohdsi.github.io/TheBookOfOhdsi/CommonDataModel). For More info check out https://ohdsi.org/software-tools/

https://github.com/OHDSI/Tutorial-ETL 

Any issues - please review for prior solutions at http://forums.ohdsi.org/[↩︎](https://ohdsi.github.io/TheBookOfOhdsi/ExtractTransformLoad.html#fnref37)  and https://forums.ohdsi.org/c/implementers[↩︎](https://ohdsi.github.io/TheBookOfOhdsi/ExtractTransformLoad.html#fnref38)

**Comment by kvegesan-stjude** [comment]
Following install instructions from : https://github.com/OHDSI/Broadsea

**Comment by kvegesan-stjude** [comment]
Finished Postgres and Atlas setup
