### ISSUE TITLE
Import OHDSI Standardized Vocabularies

### ISSUE THREAD

**Issue by RaghaSrinivasan** [stjude-biohackathon/KIDS23-Team3#8]
* Ragha preselected a few essential vocabularies from ATHENA and submitted download request on April 26, 2023. This can be used to refresh Azure VM and Hematology Server vocabularies with help from Kasi or others.
* Download all check marked libraries from Athena and add others
* CPT4 needs additional steps to login to UMLS and then use an APIKEY
* https://github.com/OHDSI/CommonDataModel/tree/v5.3.1
Refer to OHDSI Book Chapter - https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html

Please download and load the Standardized Vocabularies as following:
1.	Click on this LINK from your email to download the zip file (do not share the link per OHDSI). Typical file sizes, depending on the number of vocabularies selected, are between 30 and 250 MB. 
2.	Unpack.
3.	Reconstitute CPT-4. See below for details.
4.	If needed, create the tables.
5.	Load the unpacked files into the tables.
Important: All vocabularies are fully represented in the downloaded files with the exception of CPT-4: OHDSI does not have a distribution license to ship CPT-4 codes together with the descriptions. Therefore, we provide you with a utility that downloads the descriptions separately and merges them together with everything else. After unpacking, simply open a command line in the directory you unpacked all the files into and run "java -Dumls-apikey=xxx -jar cpt4.jar 5". Please replace "xxx" with UMLS API KEY. 
Scripts for importing the vocabulary csv files into your OMOP CDM vocabulary tables can be found [here](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOHDSI%2FCommonDataModel%2Ftree%2Fv5.3.1&data=05%7C01%7Cragha.srinivasan%40stjude.org%7C3ba090c447484126f57808db4687eb23%7C22340fa892264871b677d3b3e377af72%7C0%7C0%7C638181321803040899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rWbUfeIiu28xFtdWuxU%2F2PYoz0SgsZUssL%2B4tL1Vrt8%3D&reserved=0). They are provided in the respective folders, e.g. Oracle/, PostgreSQL/ and SQL Server/ for supported SQL dialects. The loading scripts are inside the subfolder VocabImport/.
If you hit problems please use the [OHDSI Forum pages](https://nam11.safelinks.protection.outlook.com/?url=http%3A%2F%2Fforums.ohdsi.org%2Fc%2Fimplementers&data=05%7C01%7Cragha.srinivasan%40stjude.org%7C3ba090c447484126f57808db4687eb23%7C22340fa892264871b677d3b3e377af72%7C0%7C0%7C638181321803040899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bQUENMhq1PzLzNLX%2FKWc6oz0wqpc4E5mNu6MLTjDhoc%3D&reserved=0), and somebody will help you.
===
Please download the latest version from ATHENA[25](https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html#fn25) and load it into your local database. ATHENA also allows faceted search of the Vocabularies.

To download a zip file with all Standardized Vocabularies tables select all the vocabularies you need for your OMOP CDM. Vocabularies with Standard Concepts (see Section [5.2.6](https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html#standardConcepts)) and very common usage are preselected. Add vocabularies that are used in your source data. Vocabularies that are proprietary have no select button. Click on the “License required” button to incorporate such a vocabulary into your list. The Vocabulary Team will contact you and request you demonstrate your license or help you connect to the right folks to obtain one.

http://athena.ohdsi.org/[↩︎](https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html#fnref25)

http://13.66.39.25/hades/auth-sign-in

RStudio Sign In

uname: ohdsi password: mypass

**Comment by lindsayevanslee** [comment]
Task marked done in the Project, so closing this issue
