### ISSUE TITLE
OHDSI Tools - ACHILLES 

### ISSUE THREAD

**Issue by RaghaSrinivasan** [stjude-biohackathon/KIDS23-Team3#9]
Verify Install

Introductory Tutorials

 https://ohdsi.org/ohdsi2022-tutorial/

 https://ohdsi.org/open-source-tutorials/

Practice with use cases

Discuss OHDSI tool among team with specific relevance to Integrating SCCRIP Data in OMOP format.

From https://ohdsi.org/software-tools/ below 

ACHILLES is a software tool that provides for characterization and visualization of a database conforming to the CDM. It can also be a critical resource to evaluate the composition of CDM databases in a network. ACHILLES is an R package, and produces reports based on the summary data it generates in the “Data Sources” function of ATLAS.

ACHILLES LINKS
Documentation: Book of OHDSI – [ACHILLES tool](https://ohdsi.github.io/TheBookOfOhdsi/DataQuality.html#data-quality-in-general) and [ACHILLES in practice](https://ohdsi.github.io/TheBookOfOhdsi/DataQuality.html#achillesInPractice)
Demo: [Click Here](http://atlas-demo.ohdsi.org/#/datasources)
Installation Information: [Click Here](https://ohdsi.github.io/Achilles/#getting-started)
Source Code: [GitHub](https://github.com/OHDSI/Achilles)
“10-Minute Tutorial” Video: [Click Here](https://youtu.be/UyS-LAUql-A)

**Comment by kvegesan-stjude** [comment]
Ran ACHILLES on the CDM dataset. Reports are now available in ATLAS
